version: '3.8'

services:
  selenium-tests:
    build: .
    volumes:
      - /dev/shm:/dev/shm
      - ./report.html:/app/report.html
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - selenium-grid

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  selenium-node-chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
